apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
   name: prod
...
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: prod
  labels:
     name: prod
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
    ports:
      - containerPort: 80
...
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          
...