
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: yogeshreeppawar453/docker-repos:backendlatest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: java
          protocol: TCP
          containerPort: 8080